# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(default='expected response'),
            preserve_default=False,
        ),
    ]
